version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing AWS CLI
      - pip install --upgrade awscli
  build:
    commands:
      - echo Zipping the Lambda function
      - zip -r function.zip lambda_function.py
      - echo Updating the Lambda function
      - aws lambda update-function-code --function-name lambda-hello-world --zip-file fileb://function.zip
artifacts:
  files:
    - function.zip
